### ISSUE TITLE
Page scrolling on opening and reload

### ISSUE THREAD

**Issue by naomilago** [Sven-Bo/digital-resume-template-streamlit#1]
Hi,

After adapting this template to my profile, I faced an issue when my page scrolls down to the bottom istead of start with no scoll. With this, I am not even able to see my name and avatar, as you can see in this video. 
I search for a possible solution but couldn't find anything. Can you help me?
    

https://user-images.githubusercontent.com/55967510/187090361-f992b371-feb6-45dd-b2b9-81f01b5bfb2c.mp4

Best,
Naomi Lago

**Comment by Sven-Bo** [comment]
Well noted. I will look into this issue if I find time within the next few days. I would appreciate it if you could also raise the question in the [Streamlit forum](https://discuss.streamlit.io/) and keep me updated here. Thanks!

**Comment by naomilago** [comment]
Thanks for replying, Sven!
I just raised the question and we can find it right [here](https://discuss.streamlit.io/t/page-scrolling-on-opening-and-reload/29938).

**Comment by Sven-Bo** [comment]
Thanks for raising the question. The issue was because of using multiple headers: [Solution provided by the streamlit forum](https://discuss.streamlit.io/t/page-scrolling-on-opening-and-reload/29938/7)

I have changed the code accordingly (fa5302f5307e5e2b97e7786f0d18a12d8fa60e85):
```diff
- st.write("#")
+ st.write("\n")
````
